### ISSUE TITLE
.Net Standard version.

### ISSUE THREAD

**Issue by Ilchert** [AArnott/Validation#10]
Do you have any plans to make .Net Standard version of the library?

**Comment by AArnott** [comment]
We already have a 'dotnet' folder and dependencies, so my expectation is it should 'just work' with netstandard. Let me know if that's not the case though, and I may reactivate.

I'm not too eager to do more work toward netstandard since it's such a moving target. They keep changing their roadmap so significantly I am losing interest in pursuing them till they reach whatever goal they end up with.

**Comment by Ilchert** [comment]
Net standard is different type of project, not shared, not portable, you can see example [here](https://github.com/JeremySkinner/FluentValidation/tree/master/src) ,  also very useful article about net standard [here](https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-platform-standard.md). 

Right now it is very raw technology, but it will be realized in this month and will be cool to use your library in .net core apps.

**Comment by AArnott** [comment]
netstandard provides a new way to express portable libraries and their dependencies. I'm quite familiar with it. CoreCLR and other netstandard libraries/apps can run the portable library that this project already produces, although it *might* need an `imports` line in its project.json file.

As for CoreCLR's netstandard being realized this month, I'm interested to see what they can come up with. I'm willing to change on this as I learn more.
