### ISSUE TITLE
How ought we to verify Report methods

### ISSUE THREAD

**Issue by mwpowellhtx** [AArnott/Validation#34]
I see that ``Report`` eventually lands in ``System.Diagnostics.Debug`` territory, specifically, ``Debug.WriteLine`` and ``Debug.Assert``. With ``Trace`` reports, it is *easy(ier?)* to add listeners for verification purposes. I'm not positive that would be a better approach? Otherwise, how can we wire in to ``Debug`` areas in order to monitor for reported messages? Prima facie, I am not sure it is possible after doing a bit of digging, but I wondered about any insights you might have. Thanks...

**Comment by AArnott** [comment]
Failed `Debug.Assert` or `Debug.Fail` calls feed right into the `TraceListener` system. In fact the Assertion Failed dialog pops up directly from a particular TraceListener.

So yes, and in fact I have unit tests (...somewhere...) that add TraceListeners specifically to notice debug assert failures in order to force tests to fail in those cases. (Also in those unit tests, I suppress the assert popup dialog so that it doesn't hang my test runs).

**Comment by mwpowellhtx** [comment]
@AArnott Personally, I'd like to see those tests, because the moment I attempted to interface with ``Debug.Listeners``, in particular, I was met with, *community scorn* for daring to ask why the F the team decided to drop that API? I am basically forced to shimmy a crude interface around that instead of simply listening when ``Debug.WriteLine`` occurs.

**Comment by AArnott** [comment]
The tests that suppress the assertion dialog and verify that debug.fail is called are here:
https://github.com/microsoft/vs-validation/blob/master/src/Microsoft.VisualStudio.Validation.Tests/ReportTests.Debug.cs
