### ISSUE TITLE
Add a ValidElements method to Requires

### ISSUE THREAD

**Issue by scottdorman** [AArnott/Validation#41]
It would be nice to have a convenience method on `Requires` which easily allows validating a collection against a predicate. This method could look similar to:

```cs
[DebuggerStepThrough]
public static void ValidElements<T>([ValidatedNotNull] IEnumerable<T>? values, Predicate<T> predicate, string parameterName, string message)
{
    if (predicate is null)
    {
        throw new ArgumentNullException(nameof(predicate));
    }

    if (values is object)
    {
        foreach (T value in values)
        {
            if (!predicate(value))
            {
                throw new ArgumentException(message, parameterName);
            }
        }
    }
}
```

This could then be used like
```cs
public void SetFieldWidths(params int[] fieldWidths)
{
    Requires.NotNullOrEmpty(fieldWidths, nameof(fieldWidths));
    Requires.ValidElements(fieldWidths.SkipLast(1), fw => fw >= 0, "All width's except the last must be greater than 0", nameof(fieldWidths));
}
```

**Comment by AArnott** [comment]
The use case sounds good. One reservation I have with it is that it guarantees an allocation or two at the start of a method due to allocating an `IEnumerator<T>` and possibly boxing a struct that implements `IEnumerable<T>` (e.g. `ImmutableArray<T>`). But we have precedent for that already in terms of `Requires.NotNullOrEmpty<T>`.

Would you care to send a PR? You already have the code. :)

**Comment by scottdorman** [comment]
Yes, I'll submit a PR tonight for this.

I agree about the allocation for the IEnumerator<T>, but I don't know any other way to do it and there is a precedent already. My original implementation used the LINQ Any extension, but I opted to not use it here.
